In [18]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np


model = keras.Sequential(
    [
 #       layers.Dense(1, activation="linear"),
 #       layers.Dense(5, weights=[np.ones((4, 5)), np.zeros(5)], input_dim=4, activation="relu"),
        layers.Dense(3, activation="tanh"),
        layers.Dense(1, activation="sigmoid"),
    ]
)  # No weights at this stage!

# At this point, you can't do this:
# model.weights

# You also can't do this:
# model.summary()

# Call the model on a test input
x = tf.ones((1, 4))
y = model(x)
print("model paramters:", model.weights)
print("output: ", y)
model.summary()

model paramters: [<tf.Variable 'dense_19/kernel:0' shape=(4, 3) dtype=float32, numpy=
array([[-0.49285796, -0.7664308 ,  0.86721003],
       [-0.13855326,  0.47641003,  0.6677153 ],
       [-0.10909426,  0.9132587 , -0.17168128],
       [-0.62305385, -0.9083372 , -0.06293267]], dtype=float32)>, <tf.Variable 'dense_19/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>, <tf.Variable 'dense_20/kernel:0' shape=(3, 1) dtype=float32, numpy=
array([[ 1.2156516 ],
       [-0.12232983],
       [-0.38328993]], dtype=float32)>, <tf.Variable 'dense_20/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]
output:  tf.Tensor([[0.20379394]], shape=(1, 1), dtype=float32)
Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_19 (Dense)            (1, 3)                    15        
                                                                 
 dense_20 